### PR TITLE
Fix the rare error "data.sort() is not a function"

### PR DESCRIPTION
**Pull request by rishi-s8**
There is almost no way to check the error or the fix. But I hope this works.

### CODE REVIEW

**Comment by abhigyank** [comment]
Lol nice fix. Were you able to reproduce the error?

**Comment by rishi-s8** [comment]
Nope. I tried more than 180 times. No errors.

**Comment by abhigyank** [comment]
The fix assumes that the request failure occues only once. But still worth something.

**Comment by rishi-s8** [comment]
Yes. Because the request failure had occured only once in more than 400 requests overall. So I think it is a nice assumption. And anyways, we can't keep on retrying.

**Review by abhigyank — APPROVED** [review]

**Pull request merged**
