### PR TITLE
improved project_contributors page

### LINKED ISSUE #81: Poor styling in project_contributors page
Body size inadequate, scrolls horizontally. Bold blue underline on project links looks a bit messy!

### PR DESCRIPTION
**Pull request by LalitNM**
I tried to fix #81. Please let me know if it can be improved further.
Changes:
- Fixed bug of horizontal scroll.
- Removed top image behind title, now it looks more clean.

### CODE REVIEW

**Comment by LalitNM** [comment]
Thanks @kpbot, I ammended my last commit.

**Comment by LalitNM** [comment]
@kartik1000 can you have a look on this.

**Comment by kartik1000** [comment]
Yeah sure!

**Comment by kartik1000** [comment]
@LalitNM The changes look good!. The previous UI was not in sync with the rest of the pages. Hey there is an issue. Can you update Shrikha's and HitRam's picture?
Screenshot 2020-10-05 at 4 23 45 PM

**Comment by LalitNM** [comment]
@kartik1000 We use a web scraping here using github's api, the picture of a contributor is same as the profile picture of that contributor on github. So, in order to update picture of any contributor they have to upload another picture of themselves on github. Do you want me to manually add pictures on this page?

**Comment by kartik1000** [comment]
Yeah if you can overwrite the same for these two. Please do so.

**Comment by LalitNM** [comment]
I updated the PR @kartik1000. A screenshot:
image

**Comment by abhigyank** [comment]
> Yeah if you can overwrite the same for these two. Please do so.

@kartik1000 Wouldn't this require hard-coding of code? I don't suppose that's a good practice, what do you think?

**Comment by kartik1000** [comment]
@abhigyank Well, I am sure many of our juniors won't know Hitesh sir and it would be great if they can see him :) Although, this is hard coding but since we are over-writing, I don't think it will cause an issue within the main algorithm of web scraping.

**Comment by abhigyank** [comment]
@kartik1000 Ping Hitesh to put a DP on GitHub 😁

@HitRam Please put a DP on GitHub 😛

**Comment by LalitNM** [comment]
@kartik1000 I removed unnecessary code which was used to override github api, have a look.

**Comment by vsvipul** [comment]
@kartik1000

**Comment by kartik1000** [comment]
@LalitNM Good Work. Looks good to me. Merging :)

**Pull request merged**
