### PR TITLE
Seperate contracts from gsoc

### PR DESCRIPTION
**Pull request by Milind712000**

### CODE REVIEW

**Comment by vsvipul** [comment]
I see an open PR by @mehjar why was this opened @Milind712000  ?

**Comment by Milind712000** [comment]
ye changes pdi hui thi to pr mar di

**Comment by abhigyank** [comment]
@vsvipul any changes required in the other PR or this for not merging?

**Comment by vsvipul** [comment]
@Milind712000  can you attach a screenshot for the changeS?

**Comment by vsvipul** [comment]
Closing this in favor of @mehjar 's PR.

**Pull request closed without merging**
