### PR TITLE
Insert NavBar links and Footer

### PR DESCRIPTION
**Pull request by rishi-s8**
- Add NavBar Links
- Add footer
- Remove gsoc.css
- Change colour of social links
- Change Padding of Organization Text
- Replace Line breaks with margin

* Font-weight for navBar and footer could not be fixed after multiple tries. Someone else should look into it.

### CODE REVIEW

**Comment by akshat157** [comment]
a screenshot in desktop view and a screenshot in mobile view please.

**Comment by rishi-s8** [comment]
screen shot 2018-07-01 at 12 30 17 pm
screen shot 2018-07-01 at 12 30 00 pm
screen shot 2018-07-01 at 12 29 53 pm
screen shot 2018-07-01 at 12 28 41 pm
screen shot 2018-07-01 at 12 28 35 pm
screen shot 2018-07-01 at 12 28 29 pm

**Comment by rishi-s8** [comment]
I'll fix the footer responsiveness.

**Comment by abhigyank** [comment]
I don't find any issue with the font-weights.

**Comment by akshat157** [comment]
I see two possibilities for correction.
1. footer responsiveness.
2. Font size / weight on banner for mobile devices.

Otherwise, it looks great! :smile:

**Comment by abhigyank** [comment]
Everything looks good to me. The footer on both the pages for mobile can be improved, but I think that'd be another issue. 
P.S. ignore the codacy bot comments.

**Pull request merged**
