### PR TITLE
Added About Section

### LINKED ISSUE #22: Add about section
In the home page, we should get started by adding the about section. 
The content is up to discussion here or in Zulipchat. I feel it can go something like this - 
"KamandPrompt is the student programming club that tries to innovate and foster technical activities and create a coding culture in fields like competitive programming and development. We develop cool stuff that benefits everyone in the campus, organise programming contests, hackathons, coding classes, prepare of ACM ICPC, GSoC etc. The club brings people together that are interested in honing their skills in programming and contribute towards the society."

### PR DESCRIPTION
**Pull request by rishi-s8**
fixes: #22
An About Us Section has been added to the home page and the NavBar About link has been removed. The About section is also fixed to be completely responsive.

### CODE REVIEW

**Review by abhigyank — COMMENTED** [review]
Looks good. Why remove the "About Us from the navbar"? On clicking it should scroll to the aboutus section?
Plus, in the text in the about us section, I feel each should end with a "." (fullstop) and not "!",

**Comment by rishi-s8** [comment]
Okay. Will make these changes ASAP.

**Comment by abhigyank** [comment]
Everything looks fine now. @rishi-s8 Is it possible to add smooth scroll to scroll to the about section on clicking it, rather than directly jumping to the about section? If not, then also it is fine. :)

**Comment by rishi-s8** [comment]
Possible, but in a later PR? Not very comfortable with JS right now. :)

**Comment by abhigyank** [comment]
Okay cool. Then we can merge this.

**Comment by abhigyank** [comment]
Thanks @rishi-s8 :tada: . Good job!
After adding all the sections maybe we can look into adding smooth scrolling.

**Comment by rishi-s8** [comment]
Yes we can. 👍

**Pull request merged**
