### PR TITLE
seperated contracts from GSoC section

### PR DESCRIPTION
**Pull request by mehjar**

### CODE REVIEW

**Comment by vsvipul** [comment]
@mehjar can you attach a screenshot for the changeS?

**Comment by mehjar** [comment]
change1
change2

These are the changes @vsvipul

**Comment by mehjar** [comment]
> @mehjar can you attach a screenshot for the changeS?

change1
change2

**Comment by vsvipul** [comment]
@abhigyank Is this way to do it fine?

**Comment by abhigyank** [comment]
Hmm, could be fine. Anything you decide here is fine.

**Comment by vsvipul** [comment]
Merged Thanks @mehjar

**Pull request merged**
