### PR TITLE
Add Team section

### PR DESCRIPTION
**Pull request by Varunvaruns9**
Fixes: #24 
Added Coordinator, ACM Chapter and Webdevs section.
Added pics of Abhigyan and Varun.
Other pics can be added after everyone sends them as many profile pics are guarded.

### CODE REVIEW

**Comment by akshat157** [comment]
Can you provide a screenshot for the layout?

**Comment by Varunvaruns9** [comment]
screen shot 2018-06-26 at 8 15 22 pm
screen shot 2018-06-26 at 12 02 15 pm
Sure!

**Comment by abhigyank** [comment]
I think smaller images would look better?

**Comment by Varunvaruns9** [comment]
screen shot 2018-06-26 at 8 23 47 pm
screen shot 2018-06-26 at 8 23 53 pm
@akshat157 Uploaded wrong images in previous comment, these are the new ones.

**Comment by Varunvaruns9** [comment]
Okay. Any hover effect? @abhigyank @akshat157

**Comment by abhigyank** [comment]
Would not be necessary I think.

**Comment by akshat157** [comment]
I was looking for some, but yes, it doesn't look necessary here, since the social links are placed below the display pictures. Its fine.

**Comment by Varunvaruns9** [comment]
screen shot 2018-06-26 at 9 49 45 pm
Is this fine?

**Comment by rishi-s8** [comment]
Looks good now. 👍

**Comment by abhigyank** [comment]
The images look good, but leaves too much space on the sides. Lets do this now, we can think of something better later.

**Review by rishi-s8 — APPROVED** [review]

**Comment by rishi-s8** [comment]
Merged. 👍

**Comment by abhigyank** [comment]
The github and facebook links are broken.

**Comment by Varunvaruns9** [comment]
Abhi Facebook aur Github ke links daale hi ni the

**Comment by abhigyank** [comment]
Also it'd be good to have 2/3 webdev people in the webdev part based on number of useful commits.
Need for this is because, in future if someone else commits more to this repo (lets say future batches) then they can be mentioned on the webpage while still maintaning your names ( assuming not many have contributed more useful commits to the repo).
At current standing, @rishi-s8 , @Varunvaruns9  @akshat157  looks good on the webpage.

**Pull request merged**
