### PR TITLE
Removed broken links and fixed typing error and Added Legacy Page

### PR DESCRIPTION
**Pull request by JaiLuthra1**
Broken links - Swapnil Sharma and Pinank Solanki

### CODE REVIEW

**Comment by JaiLuthra1** [comment]
@Varunvaruns9 @Swapnilr1

**Comment by Swapnilr1** [comment]
Pinank Solanki's Facebook ID seems to be https://www.facebook.com/psolanki10 so you can just update I think. Also need to remove/update his GitHub link.

**Comment by JaiLuthra1** [comment]
will do it and may I remove the github link because I can't find one?

**Comment by JaiLuthra1** [comment]
@Swapnilr1 fixed it

**Review by Varunvaruns9 — COMMENTED** [review]
Thanks for the PR and sorry for the delay @JaiLuthra1. I saw a small problem otherwise this looks good to me.

The navbar seems to break at some screen resolutions:
Screenshot 2019-09-07 at 10 27 14 PM

Also, remove the merge commit.

**Comment by JaiLuthra1** [comment]
@Varunvaruns9 please tell how to solve the issue

**Comment by Varunvaruns9** [comment]
Add some media queries here:
https://github.com/KamandPrompt/kamandprompt.github.io/blob/eab42c64b0e2b7e610fd84b8d77b890aa3b5fdb7/css/styles.css#L620

**Comment by vsvipul** [comment]
@JaiLuthra1  If you're not working on this, you should close this.

**Pull request closed without merging**
