### PR TITLE
Responsive text of navbar

### PR DESCRIPTION
**Pull request by Shrikha1**
Fix the overflow of navbar text

### CODE REVIEW

**Comment by abhigyank** [comment]
Hello @Shrikha1  thanks for the PR. Could you please explain the reasoning behind the changes? Also could this also be simply done using a responsive font-size like `em` instead of `px` ?

**Comment by Shrikha1** [comment]
To fix the overflow of the text of navbar to the next line and to avoid abrupt changes to the font size I have divided the font-size into 3 categories. And since the navbar is using float option thus using a responsive font-size like em instead of px does not give required results.

**Comment by abhigyank** [comment]
Looks fine to me. @Varunvaruns9  can you check it once before I merge this?

**Comment by Varunvaruns9** [comment]
Looks good to me. @abhigyank

**Pull request merged**
