### PR TITLE
Issue 46

### PR DESCRIPTION
**Pull request by DinahLin**
I change the CSS for Banner. I add the font in the styles.css that (text-dec) part.

### CODE REVIEW

**Comment by DinahLin** [comment]
#49 (Issue Problem)

**Comment by DinahLin** [comment]
#46 Problem Fix

**Comment by akshat157** [comment]
Hi! If its a visual addition/modification, can you include a preview here? Say a snapshot of the new design? It'd be easier to review then. :slightly_smiling_face:

**Comment by abhigyank** [comment]
@DinahLin  He means a screenshot of the webpage after the changes. It is helpful if you post those.

**Comment by abhigyank** [comment]
Not a visual improvement on the current design, hence closing.

**Pull request closed without merging**
