### PR TITLE
Made the GSOC selections collapsible and some minor adjustment of button responsiveness

### PR DESCRIPTION
**Pull request by divyashk**
Changed the font-size of the button.

## Before
Screenshot from 2020-10-03 07-45-20
## After
Screenshot from 2020-10-03 07-44-54

### CODE REVIEW

**Comment by kartik1000** [comment]
@vsvipul Is this needed? :) 
Hey @divyashk If you wish to make a small change, there is a bug on the team page that the sntc check website page button is not highlighted on toggling unlike other buttons please fix this. 
Oct-05-2020 16-39-43

**Comment by divyashk** [comment]
@kartik1000 On it bro👍

**Comment by divyashk** [comment]
@kartik1000  Kindly review it when free.
### Made the GSOC selections collapsible
## BEFORE
Screenshot from 2020-10-08 02-10-23
## AFTER
Screenshot from 2020-10-08 02-09-54
These sections are completely responsive and the code is full of comments explaining it's mechanism.

**Comment by vsvipul** [comment]
Instead of showing 9+6, I think we should show 9 Students and 6 Mentors. @divyashk

**Comment by abhigyank** [comment]
Can we have the first one open by default?

**Comment by divyashk** [comment]
> Can we have the first one open by default?

yeah sure, anything else?@abhigyank

**Comment by divyashk** [comment]
> Instead of showing 9+6, I think we should show 9 Students and 6 Mentors. @divyashk 

@vsvipul if that's what you want.

**Comment by divyashk** [comment]
### Left the first panel open and added more info on buttons about the selection's distribution.
### the page will open with this view
Screenshot from 2020-10-09 12-37-54
### on closing
Screenshot from 2020-10-09 12-38-04

**Comment by divyashk** [comment]
@vsvipul @abhigyank

**Comment by vsvipul** [comment]
Looks good, I'll leave it to @kartik1000  to review and merge.

**Comment by kartik1000** [comment]
@divyashk, Always create a new branch in your forked repo before a new pull request. Otherwise, you will end up making changes in master in your forked repo which may not be merged upstream. You can revert it but try to create a new branch right from start. I am reviewing the changes.

**Comment by divyashk** [comment]
> @divyashk, Always create a new branch in your forked repo before a new pull request. Otherwise, you will end up making changes in master in your forked repo which may not be merged upstream. You can revert it but try to create a new branch right from start. I am reviewing the changes.

@kartik1000 Will do that from now on.

**Comment by kartik1000** [comment]
@divyashk Can you adjust the layout as it was originally? I don't know if this was intentional or as a result of adding dropdowns but change it to the original one. The dropdown idea is a really good one and it makes the page more awesome. Great Work. Just make the layout changes and then we can merge
Screenshot 2020-10-12 at 6 34 39 PM

This is the original Layout.

Screenshot 2020-10-12 at 6 34 51 PM

This is the resized Layout. It is making the boxes more crowded.

**Comment by divyashk** [comment]
@kartik1000 It is fixed now.
### Before

### Now
Screenshot from 2020-10-12 19-38-09

**Comment by kartik1000** [comment]
@divyashk The changes look good. Ready to merge :)

**Comment by kartik1000** [comment]
@divyashk, There is some issue. See the GSoC page, The result is not what we see locally. I think you might have missed out some dependency which is present locally, but not on the server.

**Comment by kartik1000** [comment]
This is what we were getting locally, 
Screenshot 2020-10-13 at 5 05 34 PM
This is what we are getting now, is it the same on your system? Try to open the site and check.
Screenshot 2020-10-13 at 5 05 44 PM


It is somehow showing as expected on safari but not on chrome. Working good on chrome mobile as well. Please check @divyashk

**Comment by abhigyank** [comment]
@kartik1000 try doing a hard reload and clearing cache.

**Comment by divyashk** [comment]
@kartik1000  Even I got the same first, but ctrl+shift+R worked.

**Comment by kartik1000** [comment]
Ok, now it is working fine for me as well. Every time. Good Job 👍 . I was not aware media queries would require a hard reload :/

**Pull request merged**
